In [1]:
import numpy
import pandas
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline


In [2]:
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)


In [3]:
# load dataset
dataframe = pandas.read_csv("sonar.csv", header=None)
dataset = dataframe.values
# split into input (X) and output (Y) variables
X = dataset[:,0:60].astype(float)
Y = dataset[:,60]


In [9]:
Y.shape

(208,)

In [4]:
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)

In [5]:
# baseline model
def create_baseline():
# create model, write code below
    model = Sequential()
    model.add(Dense(60, input_dim=60, activation='relu'))
    model.add(Dense(200, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model, write code below
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    # Compile model, write code below
    return model


In [9]:
# evaluate model with standardized dataset
estimator = KerasClassifier(build_fn=create_baseline, epochs=500, batch_size=5, verbose=0)
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X,encoded_Y, cv=kfold)
print("Results: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

#End Of Step - 1 & 2
#Results: 82.71% (9.51%)

Results: 86.09% (3.23%)


In [ ]:
#Step - 3
# evaluate baseline model with standardized dataset
numpy.random.seed(seed)
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasClassifier(build_fn=create_baseline, epochs=200, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
results = cross_val_score(pipeline, X, encoded_Y, cv=kfold)
print("Standardized: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))


#Standardized: 86.97% (6.17%)
#End of Step - 3

In [ ]:
# Step - 4.1

# smaller model
def create_smaller():
    model = Sequential()
    model.add(Dense(30, input_dim=60, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model, write code below
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasClassifier(build_fn=create_smaller, epochs=100, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
results = cross_val_score(pipeline, X, encoded_Y, cv=kfold)
print("Smaller: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

#Smaller: 85.59% (6.44%)
#End of Step - 4.1

In [16]:
# Step - 4.2

# larger model
def create_larger():
    model = Sequential()
    model.add(Dense(30, input_dim=60, activation='relu'))
    #model.add(Dense(512, input_dim=60, activation='relu'))
    #model.add(Dense(256, input_dim=60, activation='relu'))
    #model.add(Dense(128, input_dim=60, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model, write code below
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasClassifier(build_fn=create_larger, epochs=5, batch_size=5, verbose=1)))
pipeline = Pipeline(estimators)
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
results = cross_val_score(pipeline, X, encoded_Y, cv=kfold)
print("Smaller: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

# Smaller: 85.47% (8.28%)
# End Of Step - 4.2

Epoch 1/5
186/186 [==============================] - 2s 10ms/sample - loss: 0.7303 - acc: 0.5269
Epoch 2/5
186/186 [==============================] - 0s 2ms/sample - loss: 0.5590 - acc: 0.7204
Epoch 3/5
186/186 [==============================] - 0s 2ms/sample - loss: 0.4673 - acc: 0.8065
Epoch 4/5
186/186 [==============================] - 0s 2ms/sample - loss: 0.4113 - acc: 0.8441
Epoch 5/5
22/22 [==============================] - 1s 28ms/sample - loss: 0.4038 - acc: 0.8182
Epoch 1/5
187/187 [==============================] - 1s 5ms/sample - loss: 0.7184 - acc: 0.5561
Epoch 2/5
187/187 [==============================] - 0s 1ms/sample - loss: 0.5318 - acc: 0.7273
Epoch 3/5
187/187 [==============================] - 0s 1ms/sample - loss: 0.4540 - acc: 0.7968
Epoch 4/5
187/187 [==============================] - 0s 2ms/sample - loss: 0.3965 - acc: 0.8235
Epoch 5/5
21/21 [==============================] - 0s 23ms/sample - loss: 0.3640 - acc: 0.9048
Epoch 1/5
187/187 [======================

NameError: name 'param_grid' is not defined

In [15]:
score

NameError: name 'score' is not defined

In [12]:
estimators()

TypeError: 'list' object is not callable

In [41]:
Pipeline

StratifiedKFold(n_splits=10, random_state=7, shuffle=True)

In [33]:
results

array([0.86363637, 1.        , 0.71428573, 0.85714287, 0.80952382,
       0.80952382, 0.95238096, 0.80000001, 0.69999999, 0.89999998])

In [8]:
X.shape

(208, 60)

In [9]:
Y.shape

(208,)

In [10]:
X[100]

array([0.0629, 0.1065, 0.1526, 0.1229, 0.1437, 0.119 , 0.0884, 0.0907,
       0.2107, 0.3597, 0.5466, 0.5205, 0.5127, 0.5395, 0.6558, 0.8705,
       0.9786, 0.9335, 0.7917, 0.7383, 0.6908, 0.385 , 0.0671, 0.0502,
       0.2717, 0.2839, 0.2234, 0.1911, 0.0408, 0.2531, 0.1979, 0.1891,
       0.2433, 0.1956, 0.2667, 0.134 , 0.1073, 0.2023, 0.1794, 0.0227,
       0.1313, 0.1775, 0.1549, 0.1626, 0.0708, 0.0129, 0.0795, 0.0762,
       0.0117, 0.0061, 0.0257, 0.0089, 0.0262, 0.0108, 0.0138, 0.0187,
       0.023 , 0.0057, 0.0113, 0.0131])

In [12]:
len(encoded_Y)

208

In [13]:
len(X)

208

In [14]:
X

array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
       [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [28]:
X[:5]

array([[0.02  , 0.0371, 0.0428, 0.0207, 0.0954, 0.0986, 0.1539, 0.1601,
        0.3109, 0.2111, 0.1609, 0.1582, 0.2238, 0.0645, 0.066 , 0.2273,
        0.31  , 0.2999, 0.5078, 0.4797, 0.5783, 0.5071, 0.4328, 0.555 ,
        0.6711, 0.6415, 0.7104, 0.808 , 0.6791, 0.3857, 0.1307, 0.2604,
        0.5121, 0.7547, 0.8537, 0.8507, 0.6692, 0.6097, 0.4943, 0.2744,
        0.051 , 0.2834, 0.2825, 0.4256, 0.2641, 0.1386, 0.1051, 0.1343,
        0.0383, 0.0324, 0.0232, 0.0027, 0.0065, 0.0159, 0.0072, 0.0167,
        0.018 , 0.0084, 0.009 , 0.0032],
       [0.0453, 0.0523, 0.0843, 0.0689, 0.1183, 0.2583, 0.2156, 0.3481,
        0.3337, 0.2872, 0.4918, 0.6552, 0.6919, 0.7797, 0.7464, 0.9444,
        1.    , 0.8874, 0.8024, 0.7818, 0.5212, 0.4052, 0.3957, 0.3914,
        0.325 , 0.32  , 0.3271, 0.2767, 0.4423, 0.2028, 0.3788, 0.2947,
        0.1984, 0.2341, 0.1306, 0.4182, 0.3835, 0.1057, 0.184 , 0.197 ,
        0.1674, 0.0583, 0.1401, 0.1628, 0.0621, 0.0203, 0.053 , 0.0742,
        0.0409, 0.0061,

In [35]:
dataset.shape

(208, 61)